### ISSUE TITLE
Jawr-grails-sample application is not working when you run it with command: grails run-app

### ISSUE THREAD

**Issue by machacekjan** [ic3fox/jawr-grails#3]
Hi,
this is probably Grails 2.4 migration problem.

**Trace**
    Line | Method
->> 1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by GroovyPagesException: Error processing GroovyPageView: Error executing tag <jawr:script>: Cannot invoke method getConfig() on null object
->>  527 | runWorker in /home/janm/Java/jawr/jawr-grails-sample/grails-app/views/index.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by GrailsTagException: Error executing tag <jawr:script>: Cannot invoke method getConfig() on null object
->>    9 | doCall    in /home/janm/Java/jawr/jawr-grails-sample/grails-app/views/index.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by NullPointerException: Cannot invoke method getConfig() on null object
->>   37 | doCall    in JawrTagLib.groovy
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     29 | doCall    in home_janm_Java_jawr_jawr_grails_sample_grails_app_views_index_gsp$_run_closure1
|     34 | run . . . in home_janm_Java_jawr_jawr_grails_sample_grails_app_views_index_gsp
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

**Comment by ic3fox** [comment]
Hi,

Can you tell me if you still get this error with the last released version (3.7)?

Cheers,

**Comment by machacekjan** [comment]
Hi,
it is working fine in the version 3.7.

Thank you
