### ISSUE TITLE
How is this better than the asset-pipeline?

### ISSUE THREAD

**Issue by hansgru** [ic3fox/jawr-grails#4]
How is this plug-in better than the AssetPipeline plug-in, and why should developers use this plug-in instead?

Thank you.

**Comment by machacekjan** [comment]
Hi, I'm using both. Asset pipeline for images, css and javascript stuff, and jawr for exporting i18n files to javascript. But if you are familiar with asset pipeline and you don't need to use your i18n in your javascript code, then there is no reason to use it.

**Comment by hansgru** [comment]
@machacekjan 

Thanks for the info.
We use i18n in JS files too, but since they don't change at runtime, we use a script to generate from each i18n property file a JS one too, so that there's no runtime overhead.

**Comment by ic3fox** [comment]
Hi,

For basic usage, you can do the same thing between Jawr and the Asset pipeline plugin. 
However I think that Jawr gives you more control on the resource generation. (using resource generator, ...), you can also generate sprites using smartsprites annotations (http://csssprites.org). 

The philosophy of these plugins are a little bit different.
You should take the one who suits your needs.

Cheers,
